enum VaporShellModule {
    VaporShell
    AccessAnalyzer
    ACMPCA
    Alexa
    AmazonMQ
    Amplify
    ApiGateway
    ApiGatewayV2
    AppConfig
    AppFlow
    AppIntegrations
    ApplicationAutoScaling
    ApplicationInsights
    AppMesh
    AppStream
    AppSync
    Athena
    AuditManager
    AutoScaling
    AutoScalingPlans
    Backup
    Batch
    Budgets
    Cassandra
    CE
    CertificateManager
    Chatbot
    Cloud9
    CloudFormation
    CloudFront
    CloudTrail
    CloudWatch
    CodeArtifact
    CodeBuild
    CodeCommit
    CodeDeploy
    CodeGuruProfiler
    CodeGuruReviewer
    CodePipeline
    CodeStar
    CodeStarConnections
    CodeStarNotifications
    Cognito
    Config
    CustomerProfiles
    DataBrew
    DataPipeline
    DataSync
    DAX
    Detective
    DevOpsGuru
    DirectoryService
    DLM
    DMS
    DocDB
    DynamoDB
    EC2
    ECR
    ECS
    EFS
    EKS
    ElastiCache
    ElasticBeanstalk
    ElasticLoadBalancing
    ElasticLoadBalancingV2
    Elasticsearch
    EMR
    EMRContainers
    Events
    EventSchemas
    FIS
    FMS
    FSx
    GameLift
    GlobalAccelerator
    Glue
    Greengrass
    GreengrassV2
    GroundStation
    GuardDuty
    IAM
    ImageBuilder
    Inspector
    IoT
    IoT1Click
    IoTAnalytics
    IoTEvents
    IoTSiteWise
    IoTThingsGraph
    IoTWireless
    IVS
    Kendra
    Kinesis
    KinesisAnalytics
    KinesisAnalyticsV2
    KinesisFirehose
    KMS
    LakeFormation
    Lambda
    LicenseManager
    Logs
    LookoutMetrics
    LookoutVision
    Macie
    ManagedBlockchain
    MediaConnect
    MediaConvert
    MediaLive
    MediaPackage
    MediaStore
    MSK
    MWAA
    Neptune
    NetworkFirewall
    NetworkManager
    OpsWorks
    OpsWorksCM
    Pinpoint
    PinpointEmail
    QLDB
    QuickSight
    RAM
    RDS
    Redshift
    ResourceGroups
    RoboMaker
    Route53
    Route53Resolver
    S3
    S3ObjectLambda
    S3Outposts
    SageMaker
    SAM
    SDB
    SecretsManager
    SecurityHub
    ServiceCatalog
    ServiceCatalogAppRegistry
    ServiceDiscovery
    SES
    Signer
    SNS
    SQS
    SSM
    SSO
    StepFunctions
    Synthetics
    Timestream
    Transfer
    WAF
    WAFRegional
    WAFv2
    WorkSpaces
}
