function Convert-SpecToCSharp {
    [CmdletBinding()]
    Param()
    Begin {
        $fullSpec = Get-CloudFormationSpecs
        $services = $fullSpec.ResourceTypes.Namespace | Sort-Object -Unique
        $SrcPath = [System.IO.Path]::Combine((Resolve-Path "$PSScriptRoot\..").Path,"src","AutoGenerated")
    }
    Process {
        foreach ($service in $services) {
            $csContents = @()
            $csPath = [System.IO.Path]::Combine($SrcPath,"$($service).cs")
            $resources = $fullSpec.ResourceTypes | Where-Object {$_.Namespace -eq $service}
            $properties = $fullSpec.PropertyTypes | Where-Object {$_.Namespace -eq $service}
            Write-Verbose "Service: $service`n`t CS Path: $csPath`n`t Resources: $($resources.Count)"
            #Set-Content -Value $csContents -Path $csPath -Encoding UTF8 -Force
        }
    }
}
