#
# Module manifest for module 'Vaporshell'
#
# Generated by: Nate Ferrell
#
# Generated on: 2/22/2017
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule            = 'Vaporshell.psm1'

    # Version number of this module.
    ModuleVersion         = '1.2.1'

    # ID used to uniquely identify this module
    GUID                  = 'd526494c-6e59-41ff-ad05-eedbc1473b6a'

    # Author of this module
    Author                = 'Nate Ferrell'

    # Company or vendor of this module
    CompanyName           = 'SCRT HQ'

    # Copyright statement for this module
    Copyright             = '(c) SCRT HQ 2017 . All rights reserved.'

    # Description of the functionality provided by this module
    Description           = 'Powershell module for building AWS CloudFormation JSON templates using Powershell syntax, abstracting working with JSON, etc.

Requires Powershell version 3.0 or higher, as it leverages ConvertTo-Json and ConvertFrom-Json to work with the template files.


**WORKS ON ALL PLATFORMS THAT CAN RUN POWERSHELL**


Recommended Additional Installs:

- AWS CLI Tools: http://docs.aws.amazon.com/cli/latest/userguide/installing.html
    - Allows you to use the -ValidateTemplate switch on Export-Vaporshell

- AWS cfn-flip: https://github.com/awslabs/aws-cfn-template-flip
    - Allows you to work with YAML for both importing templates and exporting templates.


~ ~ ~ Getting Started ~ ~ ~

http://vaporshell.io/docs


~ ~ ~ Module Digest ~ ~ ~

http://vaporshell.io/docs/digest


~ ~ ~ Examples ~ ~ ~

http://vaporshell.io/docs/examples


~ ~ ~ Change Log ~ ~ ~

http://vaporshell.io/changelog


~ ~ ~ Disclaimer ~ ~ ~

This module is only to be used to ease creation of CloudFormation templates. Any stack creations within AWS are the responsibility of the person/group deploying it, so please validate any template builds using `aws cloudformation validate-template`! ([Click here for documentation from AWS](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html))

If you find any oddities with the template build, please open an issue here on GitHub and include your script with sensitive data redacted, what you were expecting it to add to the template and what actually was added.

Thanks!
Nate Ferrell @ SCRT HQ

'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion     = '3.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture = 'None'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies    = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess      = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess        = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess      = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module
    FunctionsToExport     = '*'

    # Cmdlets to export from this module
    CmdletsToExport       = @()

    # Variables to export from this module
    VariablesToExport     = '*'

    # Aliases to export from this module
    AliasesToExport       = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList              = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData           = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = 'AWS','CloudFormation','CFN','JSON','YAML'

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            ProjectUri = 'http://vaporshell.io'

            # A URL to an icon representing this module.
            IconUri    = 'https://spotinst.com/app/themes/spotinst-theme/dist/images/features/elastigroup/intro/icons/cloudformation.svg'

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # External dependent modules of this module
            # ExternalModuleDependencies = ''

        } # End of PSData hashtable
    
    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI           = 'http://vaporshell.io/docs/'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}